export const ICON_CATALOG = {
  "target": { set: "custom" as const, variant: "stroke" },
  "shield": { set: "custom" as const, variant: "stroke" },
  "bug": { set: "custom" as const, variant: "stroke" },
  "terminal": { set: "custom" as const, variant: "stroke" },
  "lock": { set: "custom" as const, variant: "stroke" },
  "server": { set: "custom" as const, variant: "stroke" },
  "radar": { set: "custom" as const, variant: "stroke" },
  "eye": { set: "custom" as const, variant: "stroke" },
  "skull": { set: "custom" as const, variant: "stroke" },
  "key": { set: "custom" as const, variant: "stroke" },
  "network": { set: "custom" as const, variant: "stroke" },
  "braces": { set: "custom" as const, variant: "stroke" },
  "globe": { set: "custom" as const, variant: "stroke" },
  "wifi": { set: "custom" as const, variant: "stroke" },
  "bolt": { set: "custom" as const, variant: "stroke" },
  "battery": { set: "custom" as const, variant: "stroke" },
  "lucide:shield-check": { set: "lucide" as const },
  "lucide:lock": { set: "lucide" as const },
  "lucide:unlock": { set: "lucide" as const },
  "lucide:bug": { set: "lucide" as const },
  "lucide:terminal": { set: "lucide" as const },
  "lucide:code-2": { set: "lucide" as const },
  "lucide:server": { set: "lucide" as const },
  "lucide:database": { set: "lucide" as const },
  "lucide:globe": { set: "lucide" as const },
  "lucide:wifi": { set: "lucide" as const },
  "lucide:radar": { set: "lucide" as const },
  "lucide:eye": { set: "lucide" as const },
  "lucide:eye-off": { set: "lucide" as const },
  "lucide:key-round": { set: "lucide" as const },
  "lucide:cpu": { set: "lucide" as const },
  "lucide:zap": { set: "lucide" as const },
  "lucide:shield-alert": { set: "lucide" as const },
  "lucide:skull": { set: "lucide" as const },
  "lucide:network": { set: "lucide" as const },
  "lucide:layers": { set: "lucide" as const },
  "lucide:boxes": { set: "lucide" as const },
  "lucide:cloud": { set: "lucide" as const },
  "lucide:search": { set: "lucide" as const },
  "lucide:scan": { set: "lucide" as const },
  "lucide:crosshair": { set: "lucide" as const },
  "lucide:target": { set: "lucide" as const },
  "lucide:activity": { set: "lucide" as const },
  "lucide:line-chart": { set: "lucide" as const },
  "lucide:fingerprint": { set: "lucide" as const },
  "lucide:binary": { set: "lucide" as const },
  "lucide:atom": { set: "lucide" as const },
  "lucide:flame": { set: "lucide" as const },
  "lucide:rocket": { set: "lucide" as const },
  "lucide:lightbulb": { set: "lucide" as const },
  "lucide:sparkles": { set: "lucide" as const },
  "lucide:anvil": { set: "lucide" as const },
  "lucide:hammer": { set: "lucide" as const },
  "lucide:wrench": { set: "lucide" as const },
  "lucide:file-code": { set: "lucide" as const },
  "ph:shield-check": { set: "phosphor" as const },
  "ph:code": { set: "phosphor" as const },
  "ph:bug": { set: "phosphor" as const },
  "ph:lock-key": { set: "phosphor" as const },
  "ph:globe": { set: "phosphor" as const },
  "ph:cpu": { set: "phosphor" as const },
  "ph:network": { set: "phosphor" as const },
  "dev:react": { set: "dev" as const },
  "dev:typescript": { set: "dev" as const },
  "dev:javascript": { set: "dev" as const },
  "dev:python": { set: "dev" as const },
  "dev:docker": { set: "dev" as const },
  "dev:linux": { set: "dev" as const },
  "dev:kali": { set: "dev" as const },
  "dev:arch": { set: "dev" as const },
  "dev:ubuntu": { set: "dev" as const },
  "dev:figma": { set: "dev" as const },
  "dev:github": { set: "dev" as const },
  "dev:nodejs": { set: "dev" as const },
  "dev:nextjs": { set: "dev" as const },
  "dev:tailwind": { set: "dev" as const },
  "dev:remotion": { set: "dev" as const },
  "emoji:rocket": { set: "emoji" as const },
  "emoji:fire": { set: "emoji" as const },
  "emoji:shield": { set: "emoji" as const },
  "emoji:skull": { set: "emoji" as const },
  "emoji:eye": { set: "emoji" as const },
} as const;
export type CatalogName = keyof typeof ICON_CATALOG;
export const CATEGORIES = { custom: "Hand-drawn", lucide: "Lucide", phosphor: "Phosphor", dev: "Tech logos", emoji: "Emoji" } as const;
